### ISSUE TITLE
Create Xaringan Slide Theme

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/nhsrtheme#12]
Create a Xaringan slide theme that matches the NHS Identity.

**Comment by tomjemmett** [comment]
added skeleton files required, just need to update the [css](https://github.com/nhs-r-community/nhsrtheme/blob/master/inst/rmarkdown/templates/nhsr-presentation/nhsr-xaringan.css) file.

**Comment by tomjemmett** [comment]
Thanks @spcanelon ! 🙌

**Comment by spcanelon** [comment]
Thank **you** for the collab! 🙌
