### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by DrSHendricks** [nhs-r-community/nhsrtheme#21]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem
devtools::install_github('nhs-r-community/nhsrtheme')
Error: HTTP error 404.
  No commit found for the ref master

  Rate limit remaining: 57/60
  Rate limit reset at: 2021-07-20 13:29:00 UTC

**Comment by tomjemmett** [comment]
hi! mind sharing output of devtools::session_info()? I suspect it maybe an old version of devtools installed for you, before the default branch name changed from "master" to "main" the install_github only tried to check "master" by default, but I believe it tries both now (or it tries to grab the HEAD reference perhaps)

**Comment by DrSHendricks** [comment]
Hi Tom, thanks. 
> devtools::session_info()
- Session info --------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                     
...
...
devtools           2.0.1   2018-10-26 [1] CRAN (R 3.5.2)

**Comment by tomjemmett** [comment]
I think  the issue will be down to the old version of devtools, try running `install.packages("devtools")`, then re-running this code. It may also be worth upgrading your R if you have the rights on your machine to do that!
