### ISSUE TITLE
Should this package be renamed in the NHSRpackage format?

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRtheme#24]
Other packages are now in the format NHSRpackage rather than nhsrpackage. Should this one be renamed?

**Comment by tomjemmett** [comment]
it's a good point... I created this a fair while back and didn't think much to the name. The issue now is some people have already installed this, so renaming could be an issue. But as it isn't released, it's not the biggest issue ever. Would be good to get some thoughts/opinions from others (@ChrisBeeley, @chrismainey, happy to chime in?)

**Comment by ChrisBeeley** [comment]
I don't much like the NHSRpackage name format, but I don't think renaming is an issue- I don't think this package is in production on too many servers 😉

**Comment by Lextuga007** [comment]
😄 dare I ask what format you do like?! I just went with the NHSRpackage format as many of the packages are like that, including those on CRAN. Consistency is key 🚀

**Comment by ChrisBeeley** [comment]
Camel case, like on our repos!

**Comment by tomjemmett** [comment]
I tend to prefer snake_case, but package names can't be snake_case... I really dislike randoMcAsE (like you tend to see with capital R's in package names)... I think going to NHSR... is the best option as that's what we have used for other packages now. I'll rename this
