### ISSUE TITLE
Add RMarkdown template for slides in RStudio picker

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/NHSRtheme#26]
**Describe the solution you'd like**
My team's [Xaringan template](https://github.com/CDU-data-science-team/nottshcMethods) appears in the RStudio picker when you select "RMarkdown presentation".

Can we add that to this repo? I confess, I don't know how you do it, but @Lextuga007 does

**Comment by Lextuga007** [comment]
The templates are in the [inst](https://github.com/CDU-data-science-team/nottshcMethods/tree/main/inst/rmarkdown/templates/CDU-Data-Science-Team) folder. It does require a few files like yaml and files named `skeleton`.

**Comment by tomjemmett** [comment]
Does it not appear? It used to, the skeleton and template.yaml file are [here](https://github.com/nhs-r-community/NHSRtheme/tree/main/inst/rmarkdown/templates/nhsr-presentation)

**Comment by Lextuga007** [comment]
I've just installed the package and it appears in the From Template wizard 😃

**Comment by ChrisBeeley** [comment]
Yes, indeed, I'm an idiot and have now found it
