### ISSUE TITLE
Lack of @export of get_nhs_palette()

### ISSUE THREAD

**Issue by DCEW** [nhs-r-community/NHSRtheme#30]
### System details

    RStudio Edition : Desktop 
    RStudio Version :  v2023.06.0
    OS Version      :  Windows 10 Enterprise
    R Version       :  4.3.0

### Steps to reproduce the problem
NHSRtheme::get_nhs_palette()

### Describe the problem in detail
This function does not appear to be an exported element, the @export is missing from the roxygen2 comment bits. @return is also missing

### Describe the behavior you expected
To be able to call `NHSRtheme::get_nhs_palette()` which would return the hexadecimal codes for the palette requested?

**Comment by tomjemmett** [comment]
ah, yes, very much missing! If you want to submit a PR I'll merge it asap.

Will need to re-run `devtools::document()` in order to update the `NAMESPACE` file, but other than that should be good :-)

**Comment by DCEW** [comment]
Will do!
Just a qq - can you send me a line of code showing the proposed implementation? I've got it exporting locally, but am getting tangled trying to make some examples of it in use with a ggplot

Thanks,
Claire

Dr Claire E. Welsh AdvDSP BVMS(Hons) MSc PhD AHEA GradStat MRCVS
Principal Disease Intelligence Analyst
National Disease Registration Service
Data and Analytics, Transformation Directorate
NHS England

E. ***@***.***

[cid:024aa08b-258e-4609-8640-9e1b3a2174ab] [cid:4e1b58ce-d581-46fe-b784-481893db8673]
NHS-R Community Champion
________________________________

**Comment by tomjemmett** [comment]
Closed by #31
