### ISSUE TITLE
Hex logo

### ISSUE THREAD

**Issue by anyaferguson** [nhs-r-community/NHSRtheme#36]
As part of creating a packages page for the NHSRcommunity website https://github.com/nhs-r-community/nhs-r-community/issues/219, I've designed a hex sticker for this package. Will do a PR shortly with the code and logo, but happy to take feedback and tweak the design as desired.

**Comment by Lextuga007** [comment]
😍 Lovely! Linked to PR but left this open to add to README and pkgdown

**Comment by anyaferguson** [comment]
@Lextuga007 I've added the logo to the README and that looks fine. But it looks odd in the pkgdown and I'm not sure what to try next - maybe removing the NHSRcommunity logo? Is there a way of seeing what the pkgdown looks like before a PR, so I can test options?

**Comment by Lextuga007** [comment]
Good question. I had to look it up but https://github.com/r-lib/pkgdown?tab=readme-ov-file#usage 

```
# Preview your site locally before publishing
pkgdown::build_site()
```
It might be that the logos need resizing but I'm not sure.

**Comment by Lextuga007** [comment]
Posit have their org logo in the footnote https://tidyr.tidyverse.org/ which is reasonable.

**Comment by anyaferguson** [comment]
I've removed the NHSR community logo, so the NHSRtheme logo is showing nicely in the README and pkgdown site. 

I'm not sure how to put the NHSR community logo in the footer. I can put the words in by editing the role of NHSR community in the DESCRIPTION, but think may need a yaml file to have the logo: https://pkgdown.r-lib.org/reference/build_home.html?q=authors#authors.

**Comment by anyaferguson** [comment]
@Lextuga007 I can add the NHSR community logo in the footer, but only if I update the role of NHSR community in the DESCRIPTION to either maintainer ("cre"), authors ("aut"), and funder ("fnd"). Which would be the best option?

**Comment by Lextuga007** [comment]
Can we have more than one maintainer? Might but an idea to put it as that and then a person as well or will that not work out too well?

**Comment by anyaferguson** [comment]
Thanks @Lextuga007. Is it ok to to put NHSRcommunity as a maintainer for now whilst the discussion is ongoing?

**Comment by Lextuga007** [comment]
Yes. And I can be listed too, I'm happy with that.

**Comment by anyaferguson** [comment]
Following the discussion in https://github.com/nhs-r-community/NHSR-way/issues/168, I have not changed any roles in the DESCRIPTION and instead have a sentence at the top to say "This package is part of the NHS-R Community suite of R packages." with the NHS-R community logo too. Happy to change this if it's not quite right.

**Comment by anyaferguson** [comment]
@all-contributors please add @anyaferguson for design
